config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :contacts
    get '/about', to: 'pages#about'
    root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   
   def new
      @contact = Contact.new
   end
   
   def create
      @contact = Contact.new(contact_params)
      
      respond_to do |format|
        if @contact.save
          name = params[:contact][:name]
          email = params[:contact][:email]
          body = params[:contact][:comments]
          
          ContactMailer.contact_email(name, email, body).deliver
          
          format.html { redirect_to new_contact_path, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @contact }          
        else
          format.html { redirect_to new_contact_path, notice: 'Post was invalid.' }
          format.json { render json: @contact.errors, status: :unprocessable_entity }          
        end
      end      
   end
   
   private
   def contact_params
      params.require(:contact).permit(:name, :email, :comments) 
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.haml
- flash.each do |key,value|
  = content_tag :div, value, class: "alert alert-info"

.row
  .col-md-4.col-md-offset-4
    .well
      = form_with(model: @contact) do |f|
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
     
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control'
        
        .form-group
          = f.label :comments
          = f.text_area :comments, class: 'form-control'
        .actions{class: 'form-group'}
          = f.submit 'Submit', class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dev Match
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript'
    = javascript_include_tag 'application'
    = tag :meta, :name => 'stripe-key', :content => STRIPE_PUBLIC_KEY
  %body
    %nav.navbar.navbar-inverse.navbar-static-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => "#main-nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            %i.fa.fa-users
            Dev Match
          
        #main-nav-collapse.collapse.navbar-collapse
          .nav.navbar-nav.navbar-right
            - if current_user
              =button_to "Sign out", destroy_user_session_path, class: 'btn btn-primary navbar-btn', method: :delete
            -else
              =link_to "Log in", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "About", about_path
            %li= link_to "Contact Us", new_contact_path
        / /.navbar-collapse  
    .container
      = yield

app/views/pages/about.html.haml
%h2 About Us

app/views/pages/home.html.haml
.jumbotron.text-center
  %h1 Welcome to Dev Match
  %h3 A membership site where entrepreneurs can meet developers.
  .row
    .col-md-6
      .well
        %h2.text-center Basic Membership
        %h4 Sign up for free to get basic access to the community.
        = link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-success'
    .col-md-6
      .well
        %h2.text-center Pro Membership
        %h4 Sign up for the pro account for $10/month and get access to the community and contact information!
        = link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success'